site_name: Sriraam Iyer's Blog
nav:
  - Home: index.md
  - Travel: 
    - Airport operations VS airline operations at airport: ./travel-blogs/airport-operations-vs-airline-operations-at-airport.md
    - How can smart luggage trolleys help passengers: ./travel-blogs/how-can-smart-luggage-trolleys-help-passengers.md
    - Indigo domestic operations at Mumbai terminal-2: ./travel-blogs/indigo-domestic-operations-at-mumbai-terminal-2.md 
    - The Tata operated airlines: ./travel-blogs/the-tata-operated-airlines.md
    - What makes the Tata airlines stand out: ./travel-blogs/what-makes-the-tata-airlines-Stand-out.md
  - Electric vehicles: 
    - How and where can India build more public charging stations: ./ev-blogs/charging-stations.md
    - Ather products services: ./ev-blogs/ather-products-services.md
theme: material    
markdown_extensions:
  - md_in_html
theme:
  name: material
  custom_dir: overrides